### ISSUE TITLE
Can Azure digital-twins-explorer install on Azure Web App?

### ISSUE THREAD

**Issue by alviorlai** [Azure-Samples/digital-twins-explorer#20]
HI,

Sorry, just new here, and wondering that can Azure digital-twins-explorer install on Azure Web App?
Actually I did try it, but got many issues. such as below image.
![3073106](https://user-images.githubusercontent.com/71126350/92905632-678ed480-f456-11ea-8ce6-3f6cb2814262.png)

did anyone tried it before?

Thanks

**Comment by jamescarpinter** [comment]
The [Experimental Features](https://github.com/Azure-Samples/digital-twins-explorer#experimental-features) section in the readme covers running the app in an Azure Function. If you'd prefer to use an Azure Web App, the commands would be very similar (i.e. `az webapp` rather than `az functionapp`).

The error in the screenshot appears to be at build time. If you're trying to execute it on Azure Web Apps, I'd suggest following the readme instructions and instead build it locally before publishing the output to your site.

I hope this helps. I'll close the issue for now but please let us know if you run into issues!
