### ISSUE TITLE
[Bug] Twin properties crash when expanding components

### ISSUE THREAD

**Issue by uriel-kluk** [Azure-Samples/digital-twins-explorer#218]
Instances of models with components crash the explorer when inspecting the component:
![image](https://user-images.githubusercontent.com/41210115/137547780-7712b7a6-4f7d-4f16-87bf-ec3d5f9a79aa.png)

![image](https://user-images.githubusercontent.com/41210115/137547940-e317ec0e-bf72-4514-bc7b-a97bf39de9d5.png)

Some components do expand, but cellular and notifications throw the error

**Comment by ccrowley96** [comment]
Is this on latest main / hosted explorer?

**Comment by ccrowley96** [comment]
@uriel-kluk looks like this bug is caused by enumValues with localized displayName properties, rather than string displayNames.  We'll get a fix out for this asap to support localized displayName objects on enums.

If you want a workaround - for the time being, updating the models to remove localized displayNames on enum values should fix this.
