### ISSUE TITLE
complex properties removed each time some other property is updated

### ISSUE THREAD

**Issue by franpb90** [Azure-Samples/digital-twins-explorer#220]
We have been using ADT Explorer for 6 months using RealEstateCore Ontology (https://github.com/Azure/opendigitaltwins-building/tree/master/Ontology). 

We are using externalIds property that is a complex property of type 'Map'
`    {
      "@type": "Property",
      "displayName": {
        "en": "External IDs"
      },
      "name": "externalIds",
      "dtmi:dtdl:property:schema;2": {
        "@type": "Map",
        "dtmi:dtdl:property:mapKey;2": {
          "name": "externalIdName",
          "schema": "string"
        },
        "dtmi:dtdl:property:mapValue;2": {
          "name": "externalIdValue",
          "schema": "string"
        }
      },
      "writable": true
    }`

Since the 18th of October, using the ADT Explorer of the Azure Portal (https://explorer.digitaltwins.azure.net/) we have experienced this warning:
![image](https://user-images.githubusercontent.com/6066102/137859474-bafced1c-f659-4852-a12f-4fde052b44ac.png)

If we use this ADT Explorer version, it deletes the property. I understand it is comparing the twin with the model,  but until this other feature https://github.com/Azure-Samples/digital-twins-explorer/issues/164 about editing complex properties, is completed, it is a problem to work with complex properties.

**Comment by ccrowley96** [comment]
In the new property inspector, un-modelled 'floating' properties are removed on the next patch event.  This is because the ADT API doesn't allow patching properties when the twin doesn't match the shape of the model.

It looks to me like the model for the twin you shared is missing the `externalIds` map property in it's interface.  If that's the case, this doesn't look like a bug to me, but rather the intended experience.  If `externalIds` is on the model interface for that twin, can you share the models being used?

The updated property inspector adds support for the asks mentioned in #164 - with support for maps, objects, and enum editing.
