### ISSUE TITLE
Chrome fails to open http://localhost:3000/ due to SSL error

### ISSUE THREAD

**Issue by mmaitre314** [Azure-Samples/digital-twins-explorer#73]
After running `npm run start`, Chrome opens and blocks the connection to the local server:

![image](https://user-images.githubusercontent.com/8584604/99471310-20f8a300-28fb-11eb-98b5-f53357730c6b.png)

Things work fine in Edge.

It looks like with Chrome the server returns a 307 redirecting http://localhost:3000/ to https://localhost:3000/ and the latter does not work because of no SSL cert being configured.

![image](https://user-images.githubusercontent.com/8584604/99471509-8f3d6580-28fb-11eb-9bba-c24d581c904e.png)

**Comment by jamescarpinter** [comment]
This may have been caused by HSTS. You may be able to resolve it through clearing localhost from the domain security policies. The following links might help: [HTTPS redirect](https://stackoverflow.com/questions/25277457/google-chrome-redirecting-localhost-to-https/43354790) and [Non-Authoritative-Reason](https://stackoverflow.com/questions/34108241/non-authoritative-reason-header-field-http#:~:text=The%20Non%2DAuthoritative%2DReason%20%3A,to%20tell%20HSTS%20is%20enabled.&text=All%20this%20is%20done%20since,Security%20header%20on%20your%20server.). If not, please let us know!
