### ISSUE TITLE
AuthenticationError trying to reuse credentials from az-cli

### ISSUE THREAD

**Issue by rido-min** [Azure-Samples/digital-twins-explorer#78]
Running in WSL2 with node LTS (15.3.0)

I installed az-cli (2.15.1) and authenticated with `az login` and selected the same subscription with my ADT instance.

After `npm run start` I got

```
AuthenticationError: ManagedIdentityCredential authentication failed.(status code 400).
More details:
request to http://169.254.169.254/metadata/identity/oauth2/token?resource=https%3A%2F%2Fdigitaltwins.azure.net&api-version=2018-02-01 failed, reason: connect ECONNREFUSED 169.254.169.254:80
    at ManagedIdentityCredential.<anonymous> (/home/rido/code/digital-twins-explorer/client/node_modules/@azure/identity/dist/index.js:1077:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/rido/code/digital-twins-explorer/client/node_modules/@azure/identity/node_modules/tslib/tslib.js:112:69)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by jamescarpinter** [comment]
Thanks for reporting this issue. This particular configuration, WSL2 with Node, isn't something we typically test against. Our authentication pattern uses the `DefaultAzureCredential` and it appears it is falling back to `ManagedIdentityCredential` rather than the Azure CLI. We'll take a look and see if there's a fix.

**Comment by jamescarpinter** [comment]
Two follow up questions:
1. Is your source code on the WSL partition or on your Windows drive?
2. Did you install and log into the Azure CLI in Linux or in Windows?

**Comment by deomaximo** [comment]
I'm running in this very same problem using docker.

**Comment by apkolhe** [comment]
updating @azure/identity to 1.2.0-beta.2 resolved this issues for me

**Comment by deomaximo** [comment]
> updating @azure/identity to 1.2.0-beta.2 resolved this issues for me

How did you do that?

**Comment by apkolhe** [comment]
locate package.json inside client folder.  Under dependencies update @azure/identity from "@azure/identity": "^1.1.0" to "^1.2.0-beta.2" save and run "npm install" command. This should update the package. This is related to https://github.com/Azure/azure-sdk-for-js/issues/11451#issuecomment-705247729 and fixed in @azure/Identity@1.2.0-beta.2

**Comment by deomaximo** [comment]
> locate package.json inside client folder. Under dependencies update @azure/identity from "@azure/identity": "^1.1.0" to "^1.2.0-beta.2" save and run "npm install" command. This should update the package. This is related to [Azure/azure-sdk-for-js#11451 (comment)](https://github.com/Azure/azure-sdk-for-js/issues/11451#issuecomment-705247729) and fixed in @azure/Identity@1.2.0-beta.2

Thank you for the quick response! I'll give it a try.

**Comment by jamiewilbraham** [comment]
Hi @rido-min ,

We have updated the version in the development branch which should address the issue. https://github.com/Azure-Samples/digital-twins-explorer/commit/4d12abfe3fb6fc074a480e34cd111f3b9a5fee7a

Will leave open until merged into main

Thanks

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
